Q 1. Difference in the data type of variables list_ and array_list.

In the provided code, the variable list_ is a Python list containing string elements, while array_list is a NumPy array. The difference in data types is that the elements in the list are of type string, whereas the elements in the NumPy array would be of type numpy.str_.

To print the data types of both variables,we can use the type() function. Here's an example code:-

In the provided code, the variable list_ is a Python list containing string elements, while array_list is a NumPy array. The difference in data types is that the elements in the list are of type string, whereas the elements in the NumPy array would be of type numpy.str_.

To print the data types of both variables, you can use the type() function. Here's an example code snippet:

In [11]:
import numpy as np
list_ = ['1', '2', '3', '4', '5']
array_list = np.array(object=list_) 

In [4]:
print(type(list_))

<class 'list'>


Q 2.  Write a code to print the data type of each and every element of both the variables list_ and
arra_list.

In [5]:
print("Data type of array_list:", type(array_list))

Data type of array_list: <class 'numpy.ndarray'>


In [6]:
import numpy as np

In [8]:
list_ = ['1', '2', '3', '4', '5']
array_list = np.array(object=list_)

In [9]:
print("Data types of elements in list_:")
for element in list_:
    print(type(element))


Data types of elements in list_:
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>


In [10]:
print("Data types of elements in array_list:")
for element in array_list:
    print(type(element))

Data types of elements in array_list:
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>


Q 3.Changes in the variable, array_list:

In [13]:
import numpy as np

num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]

num_array = np.array(object = num_list)

In [15]:
print("Data types in the nested list:")
for sublist in num_list:
    for element in sublist:
        print(type(element))

Data types in the nested list:
<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>


In [16]:
print("Data types in the NumPy array:")
for element in num_array.flatten():
    print(type(element))

Data types in the NumPy array:
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>


In [17]:
array_list = np.array(object = list_, dtype = int)

In [18]:
print("Data types in the nested list:")
for sublist in num_list:
    for element in sublist:
        print(type(element))

Data types in the nested list:
<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>


In [19]:
print("Data types in the NumPy array:")
for element in num_array.flatten():
    print(type(element))

Data types in the NumPy array:
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>


Q.4 Code to find the Shape and Size characteristics of variable, num_array

In [20]:
import numpy as np

num_list = [[1, 2, 3], [4, 5, 6]]
num_array = np.array(object=num_list)
shape = num_array.shape
size = num_array.size
print("Shape of num_array:", shape)
print("Size of num_array:", size)

Shape of num_array: (2, 3)
Size of num_array: 6


Q 5. Code for creating arry 3*3

In [21]:
import numpy as np
zeros_array = np.zeros((3, 3))
print(zeros_array)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


Q 6.Create an identity matrix of shape (5,5) using numpy functions?

In [23]:
import numpy as np
identity_matrix = np.eye(5)
print(identity_matrix)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
